### ISSUE TITLE
Community section adjustments

### ISSUE THREAD

**Issue by chalin** [Dindihub/docsy-starter#16]
Currently, there are two index pages under the Community section:

> <img width="397" alt="image" src="https://github.com/user-attachments/assets/4baeed82-0bb5-4a03-9af2-9d076572af4d">

I suggest the following changes:

- If @lukpueh agress to move Adoptions back under the Community section, then:
  - In the front matter of `_index.md` , add
    ```yaml
    cascade:
      type: docs
    ```
  - Move the adoptions.md page to be in the `community` section folder
- Drop the `index.md` page
- Study the implementation of the Community page from the OTel repo: https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/community/_index.md?plain=1. Copy over the `community-lists` shortcode, and use it in this project.

@lukpueh - WDYT?

**Comment by chalin** [comment]
Most of the requested changes were addressed by:

- #19 

What is left to do is to move Adoptions to be back under Community.

**Comment by Dindihub** [comment]
> Most of the requested changes were addressed by:
> 
> * [Restructure Community page #19](https://github.com/Dindihub/docsy-tuf.io/pull/19)
> 
> What is left to do is to move Adoptions to be back under Community.

@chalin Done!
