### ISSUE TITLE
Add Security as top-nav entry 

### ISSUE THREAD

**Issue by Dindihub** [Dindihub/docsy-starter#24]
Add Security as top-nav entry with Audits and Reporting issues as subsections following a recommendation on the [TUF analysis](https://github.com/cncf/techdocs/issues/274)

**Comment by chalin** [comment]
Closed by https://github.com/theupdateframework/theupdateframework.io/pull/96 - made the page a top-level of `/docs`, following the example of the OTel website -- https://opentelemetry.io/docs/security/
