### ISSUE TITLE
Getting started section path and title rename

### ISSUE THREAD

**Issue by chalin** [Dindihub/docsy-starter#27]
_Originally posted by @chalin in https://github.com/Dindihub/docsy-tuf.io/pull/20#discussion_r1733589100_

> This page shouldn't exist under `/get-started/`, but we'll address this separately. I'll file an issue.

Actually, there are a few issues to address:

- [ ] Rename the `get-started` section to `getting-started` so as to match the original TUF site
- [ ] @Dindihub, you probably based the section on the corresponding section of the OTel site, but I don't think that it makes sense here to identify "Adopters" and "Contributors" as roles here. @lukpueh WDYT?

**Comment by Dindihub** [comment]
> _Originally posted by @chalin in [#20 (comment)](https://github.com/Dindihub/docsy-tuf.io/pull/20#discussion_r1733589100)_
> 
> > This page shouldn't exist under `/get-started/`, but we'll address this separately. I'll file an issue.
> 
> Actually, there are a few issues to address:
> 
> * [ ]  Rename the `get-started` section to `getting-started` so as to match the original TUF site
> * [ ]  @Dindihub, you probably based the section on the corresponding section of the OTel site, but I don't think that it makes sense here to identify "Adopters" and "Contributors" as roles here. @lukpueh WDYT?

Hi @chalin. The Get-started section was supposed to contain information for new users to understand the project.

For context, one of the key issues that came out of the [TUF analysis](https://github.com/Dindihub/techdocs/blob/main/analyses/0012-TUF/implementation.md) was that the website did not have new user content.  So creating this section was my attempt to have a guide for new users.  I discussed it with @lukpueh and we decided to group new users into Adopters and contributors.

1. **Adopters**: Integrate TUF security properties into new and existing content delivery systems. Adopters can be classified into two categories:

- Client maintainers: depend on repository maintainers, to provide a TUF repo. And they can choose from multiple TUF client implementations (python-tuf, go-tuf, etc.) Typically, they will pick the language their client is written in.
- Repository maintainers: Use either an existing TUF repository implementation (tuf-on-ci, RSTUF), or roll their own (typically using a tuf repository library such as python-tuf, go-tuf, etc.)

2. **Contributors**: want to contribute either to the spec or documentation.
- Spec contributors
- Docs contributors

But if the section doesn't bring any value to the site I'm okay getting rid of it.

**Comment by lukpueh** [comment]
IMO the classification makes sense.

**Comment by chalin** [comment]
> IMO the classification makes sense.

If it works for @lukpueh, I'm ok keep it as is.

Though, let's fix the section path name and title to match the old site.

**Comment by chalin** [comment]
Will close this for now, and revisit later if necessary.

**Comment by chalin** [comment]
Oops, forgot that the path rename was being tracked via this issue. Reopening :)

**Comment by chalin** [comment]
I kept the page, renaming it to Getting started, but refactored the content a bit. For details, see:

- https://github.com/theupdateframework/theupdateframework.io/pull/100

which closes this issue.

**Comment by Dindihub** [comment]
> I kept the page, renaming it to Getting started, but refactored the content a bit. For details, see:
> 
> * [[docsy] Streamline and refactor Getting started section theupdateframework/theupdateframework.io#100](https://github.com/theupdateframework/theupdateframework.io/pull/100)
> 
> which closes this issue.

Noted. Thanks
