### ISSUE TITLE
New IA for docs

### ISSUE THREAD

**Issue by chalin** [Dindihub/docsy-starter#31]
Here's the current organization of pages under `docs` and my suggested rework:

<pre>
Overview
  Metadata   --> make top level, and ensure `title` is "Roles and Metadata" (drop `linkTitle`)
  Project    --> make top level and move down after Getting started
    Tap      --> move back under <b>Community</b>
  Security   --> make top level
Get started  --> rename to "Getting started" (we might not need this page after all, but we can discuss)
  Contributor --> delete
  Adopter     --> delete
History       --> make a subpage of Project
Timeline      --> make a subpage of Project
FAQ
</pre>

@lukpueh - WDYT?

**Comment by chalin** [comment]
Oh, just to be clear, "make top level" means within `/docs`. That is, for example, "Project" would move to `/docs/project`.

**Comment by JustinCappos** [comment]
TAP under community is a bit weird.  I'd like to keep that separate.  

Where is the spec at here?  

Where do we list adoptions?  Do we just omit it or is it rolled in elsewhere?

**Comment by chalin** [comment]
> TAP under community is a bit weird. I'd like to keep that separate.

@JustinCappos - if you look at the current website, TAP is under Community:

> ![image](https://github.com/user-attachments/assets/8af25408-084c-47a6-afec-672c7042e3cf)

Are you ok with leaving it there for now?

> Where is the spec at here?
> 
> Where do we list adoptions? Do we just omit it or is it rolled in elsewhere?

Just to be clear, this issue is for the Documentation section of the website. For the full Information Architecture (IA), see https://github.com/cncf/techdocs/blob/main/analyses/0012-TUF/implementation.md#proposed-information-architecture-for-the-tuf-website.

**Comment by chalin** [comment]
Transferred to:

- https://github.com/theupdateframework/theupdateframework.io/issues/93
