### ISSUE TITLE
Delete unused .png icon

### ISSUE THREAD

**Issue by chalin** [Dindihub/docsy-starter#9]
_Originally posted by @chalin in https://github.com/Dindihub/docsy-tuf.io/pull/6#discussion_r1709013239_

>  Hi. You marked this as resolved but I still see the `.png` file in the PR, and now in the repo. Was there a reason that you kept it?

**Comment by Dindihub** [comment]
> _Originally posted by @chalin in [#6 (comment)](https://github.com/Dindihub/docsy-tuf.io/pull/6#discussion_r1709013239)_
> 
> > Hi. You marked this as resolved but I still see the `.png` file in the PR, and now in the repo. Was there a reason that you kept it?

Forgot it. Removing right away. Thanks for noticing.
